# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'predict.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5 import QtCore, QtGui, QtWidgets
import json
from fridgeai import training, camera
import cv2


class Ui_Learn(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1021, 600))
        self.label.setStyleSheet("QLabel{\n"
                                 "    background-color:\"#1D283D\"\n"
                                 "}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(340, 410, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Add.setFont(font)
        self.Add.setStyleSheet("QPushButton {\n"
                               "    color: #FFFFFF;\n"
                               "    border: 4px solid #FFFFFF;\n"
                               "    border-radius: 50;\n"
                               "    }\n"
                               "")
        self.Add.setObjectName("Add")
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(610, 410, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Cancel.setFont(font)
        self.Cancel.setStyleSheet("QPushButton {\n"
                                  "    color: #FFFFFF;\n"
                                  "    border: 4px solid #FFFFFF;\n"
                                  "    border-radius: 50;\n"
                                  "    }\n"
                                  "")
        self.Cancel.setObjectName("Cancel")
        self.Item = QtWidgets.QLineEdit(self.centralwidget)
        self.Item.setGeometry(QtCore.QRect(420, 90, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Item.setFont(font)
        self.Item.setText("")
        self.Item.setObjectName("Item")
        self.Item_label = QtWidgets.QLabel(self.centralwidget)
        self.Item_label.setGeometry(QtCore.QRect(280, 90, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Item_label.setFont(font)
        self.Item_label.setObjectName("Item_label")
        self.Lifespan_label = QtWidgets.QLabel(self.centralwidget)
        self.Lifespan_label.setGeometry(QtCore.QRect(210, 200, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Lifespan_label.setFont(font)
        self.Lifespan_label.setObjectName("Lifespan_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.Add.clicked.connect(lambda: self.startLearn(MainWindow))
        self.Cancel.clicked.connect(lambda: self.closeWindow(MainWindow))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.Item_label.setText(_translate(
            "MainWindow", "<html><head/><body><p>"
            "<span style=\" color:#ffffff;\">Label :</span>"
            "</p></body></html>"))
        self.Lifespan_label.setText(_translate(
            "MainWindow", "<html><head/><body><p>"
            "<span style=\" color:#ffffff;\">Lifespan :</span>"
            "</p></body></html>"))

    def startLearn(self, Form):
        import shutil
        frames = camera.get_frames(shape=(32, 32), count=100, interval=2)
        label = self.Item.text()
        with open(os.path.join('data', 'expiry.json'), 'r') as file:
            expiry_dates = json.load(file)
        with open(os.path.join('data', 'expiry.json'), 'w') as file:
            expiry_dates[label] = self.Lifespan.text()
            json.dump(expiry_dates, file)
        os.mkdir(label)
        for i, frame in enumerate(frames):
            cv2.imwrite(os.path.join(label, 'frame{}.jpg'.format(i)), frame)
        training.send_training_data(label)
        shutil.rmtree(label)
        Form.hide()

    def closeWindow(self, Form):
        Form.hide()
