# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'predict.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from random import randint
from datetime import date, timedelta


class Ui_Manual(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1021, 600))
        self.label.setStyleSheet("QLabel{\n"
                                 "    background-color:\"#1D283D\"\n"
                                 "}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(340, 410, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Add.setFont(font)
        self.Add.setStyleSheet("QPushButton {\n"
                               "    color: #FFFFFF;\n"
                               "    border: 4px solid #FFFFFF;\n"
                               "    border-radius: 50;\n"
                               "    }\n"
                               "")
        self.Add.setObjectName("Add")
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(610, 410, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Cancel.setFont(font)
        self.Cancel.setStyleSheet("QPushButton {\n"
                                  "    color: #FFFFFF;\n"
                                  "    border: 4px solid #FFFFFF;\n"
                                  "    border-radius: 50;\n"
                                  "    }\n"
                                  "")
        self.Cancel.setObjectName("Cancel")
        self.Item = QtWidgets.QLineEdit(self.centralwidget)
        self.Item.setGeometry(QtCore.QRect(420, 90, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Item.setFont(font)
        self.Item.setText("")
        self.Item.setObjectName("Item")
        self.Lifespan = QtWidgets.QLineEdit(self.centralwidget)
        self.Lifespan.setGeometry(QtCore.QRect(420, 200, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Lifespan.setFont(font)
        self.Lifespan.setText("")
        self.Lifespan.setObjectName("Lifespan")
        self.Item_label = QtWidgets.QLabel(self.centralwidget)
        self.Item_label.setGeometry(QtCore.QRect(280, 90, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Item_label.setFont(font)
        self.Item_label.setObjectName("Item_label")
        self.Lifespan_label = QtWidgets.QLabel(self.centralwidget)
        self.Lifespan_label.setGeometry(QtCore.QRect(210, 200, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Lifespan_label.setFont(font)
        self.Lifespan_label.setObjectName("Lifespan_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.Add.clicked.connect(lambda: self.addItem(MainWindow))
        self.Cancel.clicked.connect(lambda: self.closeWindow(MainWindow))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.Item_label.setText(_translate(
            "MainWindow", "<html><head/><body><p>"
            "<span style=\" color:#ffffff;\">Item :</span></p></body></html>"))
        self.Lifespan_label.setText(_translate(
            "MainWindow", "<html><head/><body><p>"
            "<span style=\" color:#ffffff;\">Lifespan :</span>"
            "</p></body></html>"))

    def random_with_N_digits(n):
        range_start = 10**(n-1)
        range_end = (10**n)-1
        return randint(range_start, range_end)

    def addItem(self, Form):
        print("Item added manually")
        conn = sqlite3.connect(os.path.join('data', 'item.db'))
        c = conn.cursor()
        today_date = date.today()
        expired = self.Lifespan.text()
        delta = timedelta(days=int(expired))
        calc_date = today_date+delta
        range_start = 10**(2-1)
        range_end = (10**2)-1
        id = randint(range_start, range_end)
        item = (id, self.Item.text(), date.today(), calc_date)
        c.execute('insert into Inventory values (?,?,?,?)', item)
        conn.commit()
        Form.hide()

    def closeWindow(self, Form):
        Form.hide()
