# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'predict.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from fridgeai import camera, ai
import sqlite3
import os
import json
from datetime import date, timedelta


class Ui_predict(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1021, 600))
        self.label.setStyleSheet("QLabel{\n"
                                 "    background-color:\"#1D283D\"\n"
                                 "}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 80, 591, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 190, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(160, 420, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Add.setFont(font)
        self.Add.setStyleSheet("QPushButton {\n"
                               "    color: #FFFFFF;\n"
                               "    border: 4px solid #FFFFFF;\n"
                               "    border-radius: 50;\n"
                               "    }\n"
                               "")
        self.Add.setObjectName("Add")
        self.Rescan = QtWidgets.QPushButton(self.centralwidget)
        self.Rescan.setGeometry(QtCore.QRect(440, 420, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Rescan.setFont(font)
        self.Rescan.setStyleSheet("QPushButton {\n"
                                  "    color: #FFFFFF;\n"
                                  "    border: 4px solid #FFFFFF;\n"
                                  "    border-radius: 50;\n"
                                  "    }\n"
                                  "")
        self.Rescan.setObjectName("Rescan")
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(720, 420, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Cancel.setFont(font)
        self.Cancel.setStyleSheet("QPushButton {\n"
                                  "    color: #FFFFFF;\n"
                                  "    border: 4px solid #FFFFFF;\n"
                                  "    border-radius: 50;\n"
                                  "    }\n"
                                  "")
        self.Cancel.setObjectName("Cancel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Add.clicked.connect(lambda: self.addItem(MainWindow))
        self.Rescan.clicked.connect(self.rescanItem)
        self.Cancel.clicked.connect(lambda: self.closeWindow(MainWindow))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate(
            "MainWindow", "<html><head/><body><p>"
            "<span style=\" color:#fefefe;\">Would you like to add</span>"
            "</p></body></html>"))
        self.label_3.setText("")
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Rescan.setText(_translate("MainWindow", "Rescan"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))

    def addItem(self, Form):
        conn = sqlite3.connect(os.path.join('data', 'item.db'))
        c = conn.cursor()
        today_date = date.today()
        with open(os.path.join('data', 'expiry.json'), 'r') as file:
            expiry_dates = json.load(file)
        try:
            expired = expiry_dates[self.label_3.text()]
        except KeyError:
            expired = 10
        delta = timedelta(days=int(expired))
        calc_date = today_date+delta
        item = (self.label_3.text(), date.today(), calc_date)
        c.execute(
            'insert into Inventory (name, start_date, end_date)'
            ' values (?,?,?)', item)
        conn.commit()
        Form.hide()

    def closeWindow(self, Form):
        Form.hide()

    def rescanItem(self):
        while True:
            print("Scanning...")
            item = ai.predict(camera.get_frames(
                (32, 32),
                count=5,
                interval=5))
            print("Scan result: {}".format(item))
            break
        self.label_3.setText(item)
